# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.fits$|\.npy$|\.npz$|\.dat$'
      - id: end-of-file-fixer
        exclude: '\.fits$|\.npy$|\.npz$|\.dat$'
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Allow larger files for scientific data samples
      # - id: check-case-conflict
      # - id: check-merge-conflict
      # - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      # Linter
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      # Formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        files: ^spimple/
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies:
          - types-requests
          - numpy
          - astropy

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: uv run pytest tests/ --tb=short
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-push]  # Only run on push, not on every commit

# Configuration for pre-commit.ci (if using)
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
